apiVersion: v1
kind: Pod
metadata:
#  name: pod-pvc
  name: pod-pvc-2
spec:
  containers:
    - name: app
      image: alpine
      volumeMounts:
      - name: mystorage
        mountPath: /mnt
      command: ["/bin/sh"]
      args: ["-c", "sleep 100000"]
  volumes:
  - name: mystorage
    persistentVolumeClaim:
      claimName: mypvc