apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: lesson16
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: web
          image: andreykhokhlov/l1:v0.2
          ports:
          - containerPort: 8080
          # Использование Секретов в качестве переменной окружения
          env:
            - name: SECRETENV
              valueFrom:
                secretKeyRef:
                  name: first-secret
                  key: password