apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: secrets-investigation
  labels:
    app: mypod-app
spec:
  containers:
  - name: mypod
    image: andreykhokhlov/l1:v0.2
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo-volume
    secret:
      secretName: first-secret

