apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: ubuntu
  namespace: secrets-investigation
  labels:
    app: mypod-app
spec:
  containers:
  - image: ubuntu
    command: ["sleep", "3600"]
    name: ubuntu
    resources: {}
    volumeMounts:
      - name: foo-volume
        mountPath: "/etc/foo"
        readOnly: true
  volumes:
    - name: foo-volume
      secret:
        secretName: first-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

