apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-deployment
  namespace: secrets-investigation
  labels:
    app: mypod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: andreykhokhlov/l1:v0.2
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: fienvrst-secret